services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  customerservice:
    build:
      context: .
      dockerfile: CustomerService/CustomerService.Api/Dockerfile
    container_name: customerservice
    restart: unless-stopped
    expose:
      - "8080"

  productservice:
    build:
      context: .
      dockerfile: ProductService/ProductService.Api/Dockerfile
    container_name: productservice
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  orderservice:
    build:
      context: .
      dockerfile: OrderService/OrderService.Api/Dockerfile
    container_name: orderservice
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      customerservice:
        condition: service_started
      productservice:
        condition: service_started

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/PaymentService.Api/Dockerfile
    container_name: paymentservice
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      orderservice:
        condition: service_started

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    container_name: apigateway
    restart: unless-stopped
    ports:
      - "5000:8080"
    depends_on:
      customerservice:
        condition: service_started
      productservice:
        condition: service_started
      orderservice:
        condition: service_started
      paymentservice:
        condition: service_started


  frontend:
    build:
      context: .
      dockerfile: Frontend/Frontend.Ui/Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5001:8080"
    depends_on:
      apigateway:
        condition: service_started
